FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Politician Hub

Politican Hub is an API for receiving information on the people serving in Congress, Congressional committees, and recent bills that have been introduced.

## Representatives [/reps]

### List All Representatives [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "first_name": "Darin",
                "last_name": "LaHood",
                "chamber": "house",
                "gender": "M",
                "birthday": "1966-10-04",
                "party": "Republican",
                "state": "IL",
                "twitter": null,
                "youtube": null
                "website": "https://lahood.house.gov/",
                "contact_form": "http://contact-me.gov"
                "committees": ["HSII24"]
            },
            {
                "id": 2,
                "first_name": "Trent",
                "last_name": "Kelly",
                "chamber": "house",
                "gender": "M",
                "age": "1973-02-08",
                "party": "Republican",
                "state": "MS",
                "twitter": "reptrentkelly",
                "youtube": ""
                "website": "http://franks.house.gov",
                "contact_form": "http://contact-reptrentkelly.gov",
                "committees": ["HSIF","HSIF03"]
            }
        ]

## Representative [/reps/{rep_id}]

### Get a Single Representative [GET]

+ Response 200 (application/json)

        {
                "id": 2,
                "first_name": "Trent",
                "last_name": "Kelly",
                "chamber": "house",
                "gender": "M",
                "age": "1973-02-08",
                "party": "Republican",
                "state": "MS",
                "twitter": "reptrentkelly",
                "youtube": ""
                "website": "http://franks.house.gov",
                "contact_form": "http://contact-reptrentkelly.gov",
                "committees": ["HSIF","HSIF03"]
        }

## Committees [/committees]

### List All Committees [GET]

+ Response 200 (application/json)
        
        [
            {
                "id": "SSGA18",
                "name": "Federal Spending Oversight and Emergency Management",
                "chamber": "senate",
                "website": "http://hsgac.senate.gov/",
                "phone": "123-456-7890",
                "chair": "Rand Paul",
                "chair_id": 3
            },
            {
                "id": "HSII10",
                "name": "Federal Lands",
                "chamber": "house",
                "website": "http://naturalresources.house.gov/",
                "phone": "123-456-7891",
                "chair": "Tom McClintock",
                "chair_id": 4
            }
        ]

## Committee [/committee/{committee_id}]

### Get a Single Committee [GET]

+ Response 200 (application/json)

        {
            "id": "SSGA18",
            "name": "Federal Spending Oversight and Emergency Management",
            "chamber": "senate",
            "website": "http://hsgac.senate.gov/",
            "phone": "123-456-7890",
            "chair": "Rand Paul",
            "chair_id": 3
        },

## Bills [/bills]

### List All Bills [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "To adapt to changing crude oil market conditions.",
                "date_introduced": "2015-02-04",
                "committees": ["HSIF","HSIF03","HSFA","HSFA18","SSBK"],
                "sponsor": "Joe Barton",
                "sponsor_id": 10
                "status": "pending"
            },
            {
                "id": 2,
                "name": "Native American Energy Act",
                "date_introduced": "2015-01-26",
                "committees": ["HSII","HSII06","HSII24","SLIA"],
                "sponsor": "Don Young",
                "sponsor_id": 15
                "status": "pending"
            }
        ]

## Bill [/bill]

### Get a Single Bill [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "To adapt to changing crude oil market conditions.",
            "date_introduced": "2015-02-04",
            "committees": ["HSIF","HSIF03","HSFA","HSFA18","SSBK"],
            "sponsor": "Joe Barton",
            "sponsor_id": 10
            "status": "pending"
        }