FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Politician Hub

Politican Hub is an API for receiving information on the people serving in Congress, Congressional committees, and recent bills that have been introduced.

## Representatives [/reps]

### List All Representatives [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "Darin LaHood",
                "chamber": "house",
                "gender": "M",
                "age": 47,
                "party": "Republican",
                "state": "IL",
                "twitter": null,
                "committees": [4,10]
            },
            {
                "id": 2,
                "name": "Trent Kelly",
                "chamber": "house",
                "gender": "M",
                "age": 49,
                "party": "Republican",
                "state": "MS",
                "twitter": "reptrentkelly",
                "committees": [11,72]
            }
        ]

## Representative [/reps/{rep_id}]

### Get a Single Representative [GET]

+ Response 200 (application/json)

        {
                "id": 2,
                "name": "Trent Kelly",
                "chamber": "house",
                "gender": "M",
                "age": 49,
                "party": "Republican",
                "state": "MS",
                "twitter": "reptrentkelly",
                "committees": [11,72]
        }

## Committees [/committees]

### List All Committees [GET]

+ Response 200 (application/json)
        
        [
            {
                "id": "SSGA18",
                "name": "Federal Spending Oversight and Emergency Management",
                "chamber": "senate",
                "website": "http://hsgac.senate.gov/",
                "chair": "Rand Paul",
                "chair_id": 3
            },
            {
                "id": "HSII10",
                "name": "Federal Lands",
                "chamber": "house",
                "website": "http://naturalresources.house.gov/",
                "chair": "Tom McClintock",
                "chair_id": 4
            }
        ]

## Committee [/committee/{committee_id}]

### Get a Single Committee [GET]

+ Response 200 (application/json)

        {
            "id": "SSGA18",
            "name": "Federal Spending Oversight and Emergency Management",
            "chamber": "senate",
            "website": "http://hsgac.senate.gov/",
            "chair": "Rand Paul",
            "chair_id": 3
        }

## Bills [/bills]

### List All Bills [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "To adapt to changing crude oil market conditions.",
                "date_introduced": "2015-02-04",
                "committees": ["HSIF","HSIF03","HSFA","HSFA18","SSBK"],
                "sponsor": "Joe Barton",
                "sponsor_id": 10
                "result": "pending"
            },
            {
                "id": 2,
                "name": "Native American Energy Act",
                "date_introduced": "2015-01-26",
                "committees": ["HSII","HSII06","HSII24","SLIA"],
                "sponsor": "Don Young",
                "sponsor_id": 15
                "result": "pending"
            }
        ]

## Bill [/bill]

### Get a Single Bill [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "To adapt to changing crude oil market conditions.",
            "date_introduced": "2015-02-04",
            "committees": ["HSIF","HSIF03","HSFA","HSFA18","SSBK"],
            "sponsor": "Joe Barton",
            "sponsor_id": 10
            "result": "pending"
        }